In [36]:
import numpy as np
matrix=np.random.randint(0,10,(6, 4))
print(matrix)

[[3 1 1 4]
 [6 6 0 8]
 [5 7 4 8]
 [1 7 2 0]
 [1 8 4 8]
 [5 2 8 8]]


## First Method 
### Easy to understand by a Layman

In [37]:
first_row=matrix[0,:]
third_row=matrix[2,:]
fifth_row = first_row+third_row
second_row=matrix[1,:]
fourth_row=matrix[3,:]
sixth_row = second_row+fourth_row
matrix[4]=fifth_row
matrix[5]=sixth_row
print(matrix)

[[ 3  1  1  4]
 [ 6  6  0  8]
 [ 5  7  4  8]
 [ 1  7  2  0]
 [ 8  8  5 12]
 [ 7 13  2  8]]


## Second Method 
### Hard to understand by a Layman

In [38]:
matrix[4,:],matrix[5,:] = matrix[0,:] + matrix[2,:],matrix[1,:] + matrix[3,:]
print(matrix)

[[ 3  1  1  4]
 [ 6  6  0  8]
 [ 5  7  4  8]
 [ 1  7  2  0]
 [ 8  8  5 12]
 [ 7 13  2  8]]


## Third Method 
### Very Hard to understand by a Layman (Please ignore this one, don't ignore if above two are wrong)

In [39]:
matrix[[4,5]]=sum(matrix[[0,2]]),sum(matrix[[1,3]])
print(matrix)

[[ 3  1  1  4]
 [ 6  6  0  8]
 [ 5  7  4  8]
 [ 1  7  2  0]
 [ 8  8  5 12]
 [ 7 13  2  8]]
